// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0b9dde28-486f-4ca1-b0fd-de618a32ae09";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedButtonChange();
void onLEDReChange();
void onLedSosChange();

int led_button;
bool LED_re;
bool led_sos;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led_button, READWRITE, ON_CHANGE, onLedButtonChange);
  ArduinoCloud.addProperty(LED_re, READWRITE, ON_CHANGE, onLEDReChange);
  ArduinoCloud.addProperty(led_sos, READWRITE, ON_CHANGE, onLedSosChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
