// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0ab328d0-cce1-437f-97c1-b5b5eff79f87";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLatitudeChange();
void onLongitudeChange();
void onLedButtonChange();
void onMaptrackChange();
void onLEDMapChange();

String latitude;
String longitude;
int led_button;
CloudLocation maptrack;
bool LED_map;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(latitude, READWRITE, ON_CHANGE, onLatitudeChange);
  ArduinoCloud.addProperty(longitude, READWRITE, ON_CHANGE, onLongitudeChange);
  ArduinoCloud.addProperty(led_button, READWRITE, ON_CHANGE, onLedButtonChange);
  ArduinoCloud.addProperty(maptrack, READWRITE, ON_CHANGE, onMaptrackChange);
  ArduinoCloud.addProperty(LED_map, READWRITE, ON_CHANGE, onLEDMapChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
